name: Build and test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.5', '2.6.5']
    name: Test gem in ruby v${{ matrix.ruby }}
    container:
      image: ruby:${{ matrix.ruby }}-alpine
    steps:
    - uses: actions/checkout@v1
    - name: Install make and gcc
      run: |
        apk add --update make
        apk add build-base
    - name: Build with dependencies
      run: |
        gem install bundler -v 2.1
        bundle install
    - name: Test with rspec
      run: |
        bundle exec rspec spec/
    - name: Lint with rubocop
      run: |
        bundle exec rubocop
